#!/usr/bin/env bash

printf "\e[36;1m%s\e[0m\n" 'Pre-commit hook started'

#Flutter format
printf "\e[33;1m%s\e[0m\n" 'Running the Flutter formatter'
flutter format .
printf "\e[32;1m%s\e[0m\n" 'Finished running the Flutter formatter'

printf "\e[36;1m%s\e[0m\n" 'Pre-commit hook finished'